repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-json
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check .
        require_serial: true
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: pyright
        name: pyright
        entry: poetry run pyright .
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
